name = "portfolio-api"
main = "dist/src/index.js"
compatibility_date = "2024-09-23"

# Default environment (dev branch)
[vars]
CORS_ORIGIN = "https://www.dev.jackfoster.dev"

# Production environment (main branch)
[env.production]
name = "portfolio-api-prod"
vars = { CORS_ORIGIN = "https://www.jackfoster.dev" }
